spring.datasource.url=jdbc:postgresql://localhost:5432/wealth_db
spring.datasource.username=jadenaguilon
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.thymeleaf.cache=false
server.port=8080